GET http://localhost:8080/api/v1/student

###
POST http://localhost:8080/api/v1/student
Content-Type: application/json
Authorization: Basic myadmin goodpassword

{
    "name": "New User",
    "email": "newuser@email.com",
    "dob": "17-12-2000"
}